---
title: "La red"
---

Los fenómenos de decaimiento forestal están cobrando gran relevancia en un contexto de cambio climático, ya que en muchos casos, aparecen asociados a episodios de sequía y calor. El proceso de decaimiento inducido por el clima suele ocurrir de una manera no lineal, llegando a causar la muerte de los árboles, e impactando por tanto al ecosistema forestal, de una manera relativamente rápida. A pesar de que hasta ahora en general ha afectado a proporciones pequeñas del territorio, el fenómeno tiene el potencial de ser la avanzada de una situación mucho más general en un futuro próximo de cambio climático. Por tanto, el estudio de los eventos de decaimiento inducidos climáticamente es clave para determinar su impacto en los ecosistemas forestales.

La **Red Española de Decaimiento Forestal inducido por el Clima** (**ReDeC**), es una red de investigadores, pertenecientes a diferentes grupos de investigación españoles, que vienen estudiando los procecos de decaimiento forestal ocurridos en la España desde diferentes aproximaciones. Con el objetivo de poner en común el conocimiento existente de los sistemas forestales afectados en los que se está realizando trabajo de campo e investigación, se ha creado esta red, con el objetivo de avanzar en el conocimiento del decaimiento forestal, reforzar vínculos entre los grupos de investigación para promover la colaboración y el flujo de información, para ayudar a los gestores forestales a afrontar el problema del decaimiento. La red se ha constituido como grupo de trabajo dentro de la [Asociación Española de Ecología Terrestre](https://www.aeet.org/). 

Los objetivos de la red son: 

1) Identificar grupos y personas investigadoras expertas en la investigación sobre el decaimiento arbóreo. 

2) Promover el flujo de información sobre la investigación realizada, en curso y proyectada, y la colaboración entre dichos grupos y personas. Para ello el primero paso sería realizar un catálogo de sitios con decaimiento inducido por clima en los que se ha realizado o se esté realizando trabajo de campo e investigación.

3) Analizar la viabilidad de protocolos comunes y de estudios comparativos entre los diferentes sistemas de estudio (por ejemplo, sobre la atribución de señal climática a los casos de decaimiento y el papel de otros agentes como la gestión, las plagas, o el medio físico y edáfico).

4) Coordinar la monitorización y el estudio a largo plazo sobre el funcionamiento y dinámica de los bosques afectados por decaimiento.

5) Visualizar los grupos de investigación españoles sobre decaimiento forestal a nivel nacional (constituyendo un grupo de trabajo de la Asociación Española de Ecología Terrestre - [AEET](https://www.aeet.org/)) e internacional (International Union of Forest Research Organizations - [IUFRO](https://www.iufro.org/); International Tree Mortality Network - ITMN).

6) Promover la coordinación y colaboración con otros colectivos científicos, como la Sociedad Española de Ciencias Forestales, y técnicos, como los vinculados a la gestión forestal.

7) Promover el impacto en la sociedad del conocimiento generado por la investigación realizada sobre el decaimiento forestal, particularmente en los ámbitos de la gestión forestal y la conservación.
