---
title: "Estándares y Protocolos"
format: html
---

### Objetivos 
Elaboración de criterios para determinar el decaimiento forestal y sus causas climáticas y bióticas, así como sus consecuencias en los servicios ecosistémicos y en la biodiversidad. 

### Responsables
- [Antonio Gazol](../../people/gazol_burgos)
- [Cristina Acosta-Muñoz](../../people/acosta_cristina)
- [Raúl Sánchez-Salguero](../../people/sanchez_salguero)

### Hoja de Ruta
::: {.callout-tip}
## Hoja de Ruta
[Aquí](../assets/202409_nerja/estandares_atribuciones_nerja_octubre_2024.pdf) tienes la hoja de ruta/conlcusiones de la mesa de trabajo de Estándares
acordada en la [primera reunión de la red](../workshops/202409_nerja/programa.qmd)
:::

### Definición y Decálogo del Decaimiento
El grupo de trabajo de estándares y protocolos ha estado trabajando en la elaboración de una ***definición del decaimieto*** así como en un decálogo, que se ha consensuado con los demas miembros de la red durante las [segundas jornadas de ReDeC](../workshops/202510_madrid/conclusiones.qmd) celebradas en 2025. 

Puedes acceder al contenido en este enlace: [**Definición y Decálogo del Decaimiento Forestal**](../productos/decalogo/decalogo_decaimiento.qmd). 


